"""
Printable case report (self-contained HTML → PDF via the browser).

Generates a styled, self-contained HTML case report that auto-triggers the print
dialog, so the analyst saves it as a PDF — no heavy PDF library needed ($0, lean).
"""
from __future__ import annotations

import html
from typing import Any, Dict, Optional

from app.tools import sar


def _esc(x: Any) -> str:
    return html.escape(str(x if x is not None else ""))


def _rows(pairs) -> str:
    return "".join(f"<tr><td class='k'>{_esc(k)}</td><td>{_esc(v)}</td></tr>" for k, v in pairs)


def build_html_report(result: Dict[str, Any], case: Dict[str, Any],
                      review: Optional[Dict[str, Any]]) -> str:
    ev = result["evidence"]
    kyc = ev["subject_kyc"]
    facts = ev["facts"]
    tm = result["typology_match"]["best_match"]
    risk = result.get("risk", {})
    scr = result.get("screening", {})
    gnn = result.get("gnn", {})
    sar_all = sar.build_all(result, case, review)
    activity = sar_all["sar"]["suspicious_activity"]

    tx_rows = "".join(
        f"<tr><td>{_esc(t['transaction_id'])}</td><td>{_esc(t['date'])}</td>"
        f"<td>{_esc(t['sender_account'])}</td><td>{_esc(t['receiver_account'])}</td>"
        f"<td class='num'>{_esc(t['payment_currency'])} {t['amount']:,.2f}</td>"
        f"<td>{_esc(t['payment_type'])}</td></tr>"
        for t in ev["transactions"][:20]
    )
    claim_rows = "".join(f"<li>{_esc(c['statement'])}</li>"
                         for c in result.get("claims", []))
    narrative_html = _esc(result.get("narrative", "")).replace("\n", "<br/>")

    return f"""<!doctype html><html><head><meta charset="utf-8">
<title>STR Draft — {_esc(case['case_id'])}</title>
<style>
  * {{ box-sizing: border-box; }}
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; color:#111; margin:32px; font-size:12px; }}
  h1 {{ font-size:20px; margin:0 0 4px; }}
  h2 {{ font-size:13px; margin:18px 0 6px; border-bottom:2px solid #4f46e5; padding-bottom:3px; color:#4f46e5; }}
  .banner {{ background:#fff7ed; border-left:4px solid #d97706; padding:8px 12px; font-size:11px; margin-bottom:14px; }}
  .meta {{ color:#555; font-size:11px; }}
  table {{ width:100%; border-collapse:collapse; margin:4px 0; }}
  td, th {{ border:1px solid #ddd; padding:4px 6px; text-align:left; vertical-align:top; }}
  th {{ background:#f4f4f7; }}
  td.k {{ width:200px; color:#555; font-weight:600; background:#fafafa; }}
  td.num {{ text-align:right; font-variant-numeric: tabular-nums; }}
  .chip {{ display:inline-block; padding:2px 8px; border-radius:10px; font-weight:700; font-size:11px; }}
  .crit {{ background:#fee2e2; color:#b91c1c; }} .warn {{ background:#fef3c7; color:#b45309; }}
  .foot {{ margin-top:20px; color:#888; font-size:10px; border-top:1px solid #eee; padding-top:8px; }}
  @media print {{ body {{ margin:12mm; }} .noprint {{ display:none; }} }}
</style></head><body onload="setTimeout(function(){{window.print()}},400)">
<h1>Suspicious Transaction Report — DRAFT</h1>
<div class="meta">Case {_esc(case['case_id'])} · generated by ComplianceAgent · <b>not filed</b></div>
<div class="banner"><b>DRAFT — pending MLRO filing decision.</b> Prepared by an AI copilot from
synthetic data. Not a cleared or filed case. Requires human sign-off.</div>

<h2>1. Risk &amp; Assessment</h2>
<table>{_rows([
  ("Overall risk", f"{risk.get('overall_risk')} — {risk.get('risk_band')}"),
  ("Assessed typology", tm['typology_label']),
  ("Coded activity (SAR)", activity['category_code']),
  ("GNN case risk", gnn.get('case_risk')),
  ("Sanctions/PEP screening", scr.get('risk_level')),
])}</table>

<h2>2. Subject (KYC)</h2>
<table>{_rows([
  ("Name", kyc.get('full_name')), ("Account", kyc.get('account_number')),
  ("Nationality / residence", f"{kyc.get('nationality')} / {kyc.get('residence_country')}"),
  ("Risk rating", kyc.get('risk_rating')), ("PEP", 'Yes' if kyc.get('pep_flag') else 'No'),
  ("Occupation", kyc.get('occupation')), ("Source of funds", kyc.get('source_of_funds')),
])}</table>

<h2>3. Transaction Summary</h2>
<table>{_rows([
  ("Transactions", facts.get('transaction_count')),
  ("Aggregate value", f"{(facts.get('currencies') or ['AED'])[0]} {facts.get('total_amount', 0):,.2f}"),
  ("Jurisdictions", ", ".join(facts.get('involved_locations', []))),
])}</table>
<table><tr><th>Txn ID</th><th>Date</th><th>Sender</th><th>Receiver</th><th>Amount</th><th>Type</th></tr>
{tx_rows}</table>

<h2>4. Verifiable Claims</h2><ul>{claim_rows}</ul>

<h2>5. Case Narrative &amp; EDD Draft</h2>
<div style="font-size:11px;line-height:1.5">{narrative_html}</div>

<div class="foot">Filing SLA: {_esc(sar_all['sla']['status'])}. Reviewer: {_esc((review or {}).get('reviewer', 'unassigned'))}.
ComplianceAgent — draft only, not a filing.</div>
</body></html>"""
